variable "project_name" {}
variable "cluster_name" {}
variable "network_vpc" {}
variable "subnetwork" {}
variable "location" {}
variable "nodes_size" {}
variable "autoscale_min_nodes" {}
variable "autoscale_max_nodes" {}
variable "second_net_pods" {}
variable "second_net_services" {}
variable "service_account" {}